# Generated by Django 5.1.1 on 2024-09-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_post_image_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='postimage',
            name='hashtags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
